//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFExport.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFExport.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write PDF:
        ///{0}.
        /// </summary>
        internal static string Error_CoulNotWritePDF {
            get {
                return ResourceManager.GetString("Error_CoulNotWritePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FinishedDialog_Close {
            get {
                return ResourceManager.GetString("FinishedDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FinishedDialog_Open {
            get {
                return ResourceManager.GetString("FinishedDialog_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Export is finished. Do you want to open the exported PDF?.
        /// </summary>
        internal static string FinishedDialog_Text {
            get {
                return ResourceManager.GetString("FinishedDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Exporter finished.
        /// </summary>
        internal static string FinishedDialog_Title {
            get {
                return ResourceManager.GetString("FinishedDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export as PDF....
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Export by Malte Ried.
        /// </summary>
        internal static string Menu_ToolTip {
            get {
                return ResourceManager.GetString("Menu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Options_Bottom {
            get {
                return ResourceManager.GetString("Options_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Options_CancelButton {
            get {
                return ResourceManager.GetString("Options_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Options_Left {
            get {
                return ResourceManager.GetString("Options_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string Options_Margin {
            get {
                return ResourceManager.GetString("Options_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Options_OKButton {
            get {
                return ResourceManager.GetString("Options_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export only selected elements.
        /// </summary>
        internal static string Options_OnlySelected {
            get {
                return ResourceManager.GetString("Options_OnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        internal static string Options_Right {
            get {
                return ResourceManager.GetString("Options_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Export Options ähnelt.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        internal static string Options_Top {
            get {
                return ResourceManager.GetString("Options_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit ähnelt.
        /// </summary>
        internal static string Options_Unit {
            get {
                return ResourceManager.GetString("Options_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting diagram to PDF... ähnelt.
        /// </summary>
        internal static string Progress_Text {
            get {
                return ResourceManager.GetString("Progress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Export... ähnelt.
        /// </summary>
        internal static string Progress_Title {
            get {
                return ResourceManager.GetString("Progress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF-Files (*.pdf)|*.pdf ähnelt.
        /// </summary>
        internal static string SaveDialogFilter {
            get {
                return ResourceManager.GetString("SaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cm ähnelt.
        /// </summary>
        internal static string Unit_CM {
            get {
                return ResourceManager.GetString("Unit_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dots ähnelt.
        /// </summary>
        internal static string Unit_Dots {
            get {
                return ResourceManager.GetString("Unit_Dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inch ähnelt.
        /// </summary>
        internal static string Unit_Inch {
            get {
                return ResourceManager.GetString("Unit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mm ähnelt.
        /// </summary>
        internal static string Unit_MM {
            get {
                return ResourceManager.GetString("Unit_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pixel ähnelt.
        /// </summary>
        internal static string Unit_Pixel {
            get {
                return ResourceManager.GetString("Unit_Pixel", resourceCulture);
            }
        }
    }
}
